"use strict";
exports.__esModule = true;
var express_1 = require("express");
var workout_controller_1 = require("../controllers/workout-controller");
var workout_log_controller_1 = require("../controllers/workout-log-controller");
var authentication_controller_1 = require("../controllers/authentication-controller");
var router = express_1.Router();
var workoutLogController = new workout_log_controller_1.WorkoutLogController();
var workoutController = new workout_controller_1.WorkoutController();
var authenticationController = new authentication_controller_1.AuthenticationController();
router.get('/workouts', workoutController.GetAllWorkouts);
router.post('/createWorkout', workoutController.CreateWorkout);
router.get('/workout/:id', workoutController.GetWorkoutById);
router.post('/createWorkoutLog', workoutLogController.CreateWorkoutLog);
router.get('/workoutLogs', workoutLogController.GetAllWorkoutLogs);
router.get('/workoutLog/:id', workoutLogController.GetWorkoutLogById);
router.post('/register', authenticationController.Register.bind(authenticationController));
router.post('/login', authenticationController.Login.bind(authenticationController));
exports.BadassFitnessAPI = router;
//# sourceMappingURL=index.js.map